### PR TITLE
upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by anthonydahanne**

### CODE REVIEW

**Comment by anthonydahanne** [comment]
test this please
weird failure

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
@jd0-sag @myronkscott : the voltron-proxy module does not compile anymore. 

See failure at the end: https://terracotta-oss.ci.cloudbees.com/job/terracotta-platform-pull-requests/337/console

This is because this module is jdk6 and compiled with a jdk6 on cloudbee. I guess the client communicator api is now compiled jdk8 ?

@anthonydahanne : was able to reproduce locally: doing a `mvn clean install` with jdk8 works, but fails with a jdk6. So we probably need to change the Cloudbee default jdk ?

**Comment by jd0-sag** [comment]
APIs `1.0.9.beta` changed some other server-side modules to Java8, including `standard-cluster-services`.

This module normally shouldn't be seen by client-side code (where the Java6 requirement exists).  Proxy seems to mix client and server code in the same module, which is probably the issue.

**Comment by anthonydahanne** [comment]
test this please

**Comment by mathieucarbou** [comment]
Replaced by #176

**Pull request closed without merging**
