### PR TITLE
Upgrade to tc-core 5.4.0-pre6

### PR DESCRIPTION
**Pull request by mathieucarbou**
Replaces #401

### CODE REVIEW

**Comment by myronkscott** [comment]
There are some test failures.  I think they are related to missed notifications fired prior to connect.

**Comment by myronkscott** [comment]
New releases with bug fixes 

terracotta-core 5.4.0-pre7
passthrough-testing 1.4.0-pre5

**Comment by mathieucarbou** [comment]
ahah! I just saw your comment @myronkscott . I'll update the parent pom.

**Comment by mathieucarbou** [comment]
test this please

**Pull request merged**
