### PR TITLE
Issue #191 : HA and Failover Galvan tests

### PR DESCRIPTION
**Pull request by mathieucarbou**
Part of #191

### CODE REVIEW

**Comment by mathieucarbou** [comment]
Blocked by https://github.com/Terracotta-OSS/terracotta-core/issues/405

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
build failed because of the license check - missing license ;-) fixed!

**Comment by anthonydahanne** [comment]
@mathieucarbou can you please also review ?

**Comment by mathieucarbou** [comment]
@anthonydahanne : good for me! But 1 test is failing.

**Comment by anthonydahanne** [comment]
@mathieucarbou please review

**Comment by mathieucarbou** [comment]
good :+1:

**Pull request merged**
