### PR TITLE
#2203: Allow client management layer to recover after a reconnection.

### PR DESCRIPTION
**Pull request by mathieucarbou**
See: https://github.com/ehcache/ehcache3/issues/2203

# PLEASE LET @AbfrmBlr REVIEW & MERGE => he needs to test in Ehcache if the code is OK.

Changes:

- Introduced interface NmsAgentService for impl DefaultNmsAgentService.java
- DefaultNmsAgentService now request an NmsAgent entity lazily when it needs to send something to the server
- Supports a provider for NmsAgentEntity
- Supports a callback in case of connection error to be able to re-create the connection if needed
- Some other fixes.
- See: NmsAgentServiceIT

### CODE REVIEW

**Comment by chrisdennis** [comment]
Why don't you love me?

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
@chrisdennis : because... you do not have the same haircut 🤣

**Comment by mathieucarbou** [comment]
test this please

**Comment by AbfrmBlr** [comment]
test this please

**Pull request merged**
