### PR TITLE
Several improvements and tests for the monitoring service.

### PR DESCRIPTION
**Pull request by mathieucarbou**
This PR 
- follows @anthonydahanne comments on the previous PR #149 
- add some tests
- fix implementation to support passive/active

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@anthonydahanne : I need to rebase first before you merge, and also I need to add some tests regarding MonitoringService methods for notifications, stats, buffer and management calls.

**Comment by mathieucarbou** [comment]
Note: this PR currently fails because of a bug in passthrough: Terracotta-OSS/tc-passthrough-testing#36

**Comment by mathieucarbou** [comment]
@anthonydahanne : I squashed the 2 commits for tests, and I fixed 3 other test classes. I also tested against a potential fix to Terracotta-OSS/tc-passthrough-testing#36 and it works, so as soon as the passthrough issue is fixed, we will be able to merge this.

**Comment by anthonydahanne** [comment]
LGTM

**Pull request merged**
