### PR TITLE
Dynamic config fixes

### PR DESCRIPTION
**Pull request by mathieucarbou**
- Allows to see the normal server logs for Angela tests, including the system properties used at server startup.
-  Added error checks when looking at the toolchains
- Increased tests timeouts
- no more `--illegal-access=permit`
- added README.md
- Removing dead system property that was put there by mistake

### CODE REVIEW

**Comment by saurabhagas** [comment]
Needs a rebase now.

**Comment by mathieucarbou** [comment]
> Needs a rebase now.

done

**Comment by mathieucarbou** [comment]
@saurabhagas  @mobasherul  : could you please re-approve ? 
I have merged @mobasherul 's PR and rebased this one.
Thanks!

**Comment by mathieucarbou** [comment]
@saurabhagas @mobasherul : FINALLY ! All builds passed at the same time 😓

**Pull request merged**
