### PR TITLE
Fix #447: Filtering out old statistic samples

### LINKED ISSUE #447: BUG: Cache old get latencies not filtered out

### PR DESCRIPTION
**Pull request by mathieucarbou**
UPDATE: __There is some build issues on cloudbeee.__

`./mvnw clean install` pass locally -> build success

### CODE REVIEW

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by akomakom** [comment]
test this please

**Comment by akomakom** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by akomakom** [comment]
test this please

**Comment by GaryWKeim** [comment]
I have concerns about how long stats are hanging around in the client. When I discovered this defect, stats from several hours ago where still being pumped to the TMS.
_

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Pull request merged**
