### PR TITLE
Fixing artifact names (group them), scopes and missing provided apis

### PR DESCRIPTION
**Pull request by mathieucarbou**
### Rebased on #582

### CODE REVIEW

**Comment by mathieucarbou** [comment]
The change is to get the library names aligned.
Same way we have a prefix dynamic-config-*, terracotta-*, ehcache-*,
store-*, etc...

Please merge to unblock me at least and if you are really not ok with that
I suggest you bring the topic in leads
Thanks !

-- Mathieu

**Comment by saurabhagas** [comment]
@mathieucarbou my comment was along the lines of "this change isn't really needed", but it's no big deal. I can merge this PR once you rebase.

**Comment by mathieucarbou** [comment]
rebased on master

**Comment by mathieucarbou** [comment]
@saurabhagas : rebased on master

**Comment by mathieucarbou** [comment]
> @mathieucarbou my comment was along the lines of "this change isn't really needed", but it's no big deal. I can merge this PR once you rebase.

No, but it really help during the kitting because all libraries are grouped by name.

**Comment by saurabhagas** [comment]
Yes, approved. Github doesn't let you merge without a green build

**Pull request merged**
