### PR TITLE
Carry-over nomination #15

### PR DESCRIPTION
**Pull request by AbfrmBlr**

### CODE REVIEW

**Comment by alexsnaps** [comment]
You totally lost me here... is this for issue #15 ? Why is `Nomination` both used as a return value for `org.terracotta.consensus.entity.CoordinationEntity#runForElection` as well as the server to clients message ? 
Also, I may be reading this wrong, but the "continuation" of the election of a crashed client is triggered by the server when that client "delists" (but how is that wired in the `.disconnect`?), but that can't be done that way... that approach requires a client to be connected for that happen, right? But this needs to work for the single connected client crashing, and only then a new client connecting and taking over then. Now I'm not asking to add code to cover this case though!

**Comment by AbfrmBlr** [comment]
I merged both the messages since you suggested that, when we last discussed about #17.

Disconnect is already wired in to pass on to the delist of that client in the leader elector. Thus crashing of the client will lead to delist at the server side ending up in sending the continuing nomination to other in the queue.

For the second point, as of now if there was only one client which ran for election and crashed, since the queue is empty, nothing will be send to any of the clients. The new client joining will actually get a elected Nomination rather that a continuing one. I will code this through.

**Comment by AbfrmBlr** [comment]
Rebased

**Comment by AbfrmBlr** [comment]
rebased

**Comment by ljacomet** [comment]
Will not be merged as is, was fixed differently

**Pull request closed without merging**
